server:
  port: 8080
  apiOnly: False
  source: gcvit
  binSize: 500000

users:
   test1  : password

snpnamed:
  location: assets/SoySNP50k_TestFile_named.vcf.gz
  name: soySNP 50k subset [named]
  format: vcf

snpnamedr:
  location: assets/SoySNP50k_TestFile_named.vcf.gz
  name: soySNP 50k subset [named] [restricted]
  format: vcf
  restricted:
    - test1
