# Control ports and authentication certificates.
# binSize here is interpreted when running the server without the ui
server:
  port: 8080
  portTLS: 8888
  certFile: config/testcert.cert
  keyFile: config/testcert.key
  apiOnly: False
  source: gcvit
  binSize: 500000

# Optional. Add users here for authentication to control access to data sets.
users:
   user1: password1
   user2: password2
   user3: password3

# Data tracks. Must be at least one.
# Indicate data set access by listing usernames under the 'restricted' field, 
#    or remove the field entirely for unrestricted access.
snpnamed:
  location: assets/SoySNP50k_TestFile_named.vcf.gz
  name: soySNP 50k subset [named]
  format: vcf

snpnamedr:
  location: assets/SoySNP50k_TestFile_named.vcf.gz
  name: soySNP 50k subset [named] [restricted]
  format: vcf
  restricted:
    - user1

snpnamedrmulti:
  location: assets/SoySNP50k_TestFile_named.vcf.gz
  name: soySNP 50k subset [named] [multi-restricted]
  format: vcf
  restricted:
    - user2
    - user3
