server:
  port: 8080
  portTLS: 8888
  certFile : config/testcert.cert
  keyFIle : config/testcert.key
  apiOnly: False
  source: gcvit
  binSize: 500000

users:
   user1  : password1
   user2  : password2
   user3  : password3

snpnamed:
  location: assets/SoySNP50k_TestFile_named.vcf.gz
  name: soySNP 50k subset [named]
  format: vcf

snpnamedr:
  location: assets/SoySNP50k_TestFile_named.vcf.gz
  name: soySNP 50k subset [named] [restricted]
  format: vcf
  restricted:
    - user1

snpnamedrmulti:
  location: assets/SoySNP50k_TestFile_named.vcf.gz
  name: soySNP 50k subset [named] [multi-restricted]
  format: vcf
  restricted:
    - user2
    - user3
